#!/bin/bash
# MOAB/Torque submission script for SciNet GPC 
#
#PBS -l nodes=32:ppn=8,walltime=47:00:00
#PBS -N ramses
#PBS -m abe

module load intel/15.0.2 openmpi/intel/1.6.4 
# DIRECTORY TO RUN - $PBS_O_WORKDIR is directory job was submitted from
cd $PBS_O_WORKDIR

# EXECUTION COMMAND; -np = nodes*ppn
mpirun ./ramses3d input.nml > output.txt
